### ISSUE TITLE
Too many spaces (around 20) after line containing string interpolation will cause editor to crash

### ISSUE THREAD

**Issue by darthInvad0r** [aurelia/vscode-extension#79] opened 2018-02-19 02:20 UTC
**I'm submitting a bug report**

* **Extension Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Windows 7 (I have confirmed on both)

* **Visual studio code version:**
1.20.1

**HTML/JS/TS of incorrect highlight**
![image](https://user-images.githubusercontent.com/34045881/36360334-8251d9d4-156a-11e8-8453-89b66bcd7ba6.png)
note: I have render whitespace set to 'all' in this screenshot.

**Current behavior:**
Not an incorrect highlight so much as each additional space after about ~20 will cause cpu usage to spike. Simply holding down space bar should be enough to trigger a hard lock of the application

**Expected/desired behavior:**
Code to not crash when there's too much whitespace after a line featuring string interpolation

* **What is the motivation / use case for changing the behavior?**
It's annoying to have the editor crash when I backspace at the start of an empty line to remove it, only to have the whitespace append to the previous line, and cause the editor to crash.

**Update:**

The spaces do not have to be contiguous, so this bug would also hit anyone who has ~20 words after an aurelia interpolation, and on the same line.

`${a} aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` is fine
`${a} a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a` will crash
`${a} ............................................................... (spaces) ` will crash.

Possibly some error in tokenisation there somewhere.

**Comment by jmezach** [comment] 2018-02-22 09:42
Just been hit by this as well. Very nasty bug. Any ETA on a fix for this?

**Comment by darthInvad0r** [comment] 2018-02-23 04:22
Turns out this will also crash if the spaces are non-contiguous, eg `${a} a a a a a a a a a a a a a a a ... ` will eventually crash.

**Comment by jordan-ware** [comment] 2018-02-23 04:59
also no spaces don't crash:
`${a}aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...`

it seems like the `Parser` from `aurelia-binding` may be the culprit, because the regex works fine. Haven't reproduced, but it could be possible that HTML that reproduces this issue will fail at run time.

**Comment by eriklieben** [comment] 2018-02-23 10:20
Was a bit overloaded with work this week, will try to look at this weekend

**Comment by darthInvad0r** [comment] 2018-02-23 10:29
For what it's worth, the extent of the digging around I did was to pop open the dev tools in code, and adding spaces will eventually result in some timeout errors appearing, each one taking double the time as the previous.

**Comment by eriklieben** [comment] 2018-02-23 10:38
Thanks! It's probably a bug in the new way it parses the HTML. I tried turning off the autocomplete and validation to see if that would help, but it still crashes :-(

My PC crashed this week after a windows update in combination with some Dell updates or something. So I lost my set up / need to get the code and set up the debug environment first / can take a quick peek into it atm. 

I expect I can look into it tomorrow a bit before the the current time (10.00 UTC GMT+1).

**Comment by eriklieben** [comment] 2018-02-25 11:49
It's an issue with the regex for highlighting string interpolation. 

I've turned off all custom code and added back regex statements one by one to find the thing that causes it. 

It was introduced by this change: https://github.com/aurelia/vscode-extension/blob/09211588f17c81c8e5dac3949080de6946ad0a5b/syntaxes/html.json#L27-L40 when i tried to fix issue #48 

Going to look at how to fix it.

**Comment by darthInvad0r** [comment] 2018-02-26 06:01
I don't envy that problem, I don't think JS regex supports balanced pair matching.

**Comment by eriklieben** [comment] 2018-02-26 09:06
The negative lookahead worked, but I think it was too costly to do I guess, which caused the crash. Not sure why I've added that, was looking at it yesterday like "Why did I make it so complex" :-)

The issue should be resolved in v1.0.2 of the extension.

Thank you for submitting the bug report and sorry for the inconvenience it caused. It took me a bit longer, my laptop crashed again on Saturday morning and needed to get my BitLocker key to restore/ perform analytics on fixing bootup, which wasn't available until today.

**Comment by jordan-ware** [comment] 2018-02-27 05:59
Unfortunately this introduces new issues with multiple interpolations on the same line:

![image](https://user-images.githubusercontent.com/14194954/36712925-afa253d2-1bd2-11e8-930e-634d17f26b27.png)

![image](https://user-images.githubusercontent.com/14194954/36712969-e0778310-1bd2-11e8-8434-5179da8a4117.png)

**Closed** 2018-02-28 21:08 UTC
Labels: bug

**Comment by eriklieben** [comment] 2018-02-28 21:09
Tested and implemented the fix, @darthInvad0r thanks for the helping out fixing the issue!
