### ISSUE TITLE
Incorrect js code highlight

### ISSUE THREAD

**Issue by sysanin** [aurelia/vscode-extension#20] opened 2016-11-04 13:12 UTC
**I'm submitting a bug report**

* **Extension Version:**
0.1.9

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Visual studio code version:**
1.7.1

**Screenshot of incorrect highlight**
http://i.imgur.com/dEZAk3N.png

**Summary:**
Aurelia Dark+ theme incorrectly highlights js (`this` / `super` words)

**Comment by eriklieben** [comment] 2016-11-05 20:17
Thanks for the bug report.

This is caused by the new grammar/ modified themes in >1.7.0 (https://code.visualstudio.com/updates#_improved-typescript-and-javascript-grammar).

This issue will be resolved in the next release, I've updated the Aurelia themes with the changes made in the original Dark+ themes.

**Closed** 2016-11-05 20:18 UTC
Labels: bug
